jobs:
  - name: runShk7
    type: runSh
    serial: true
    steps:
      - IN: sample-script-3
      - IN: triggertest3
      - TASK:
        - script: ./IN/sample-script-3/gitRepo/echo.sh
    on_success:
      #- uname -a
      - NOTIFY: myEmail2
      - NOTIFY: mySlack2
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: mySlack2
      
  - name: runShk8
    type: runSh
   # serial: true
    steps:
      - IN: sample-script-4
      - IN: triggertest3
      - TASK:
        - script: ./IN/sample-script-4/gitRepo/echo.sh
  
 
