triggers:
  - name: triggertest3
    type: trigger
    version:
      counter: 272
      
  - name: triggertest4
    type: trigger
    version:
      counter: 0

  - name: triggertest5
    type: trigger
    version:
      counter: 0
