jobs:
  - name: runSh37
    type: runSh
    steps:
      - IN: sample-script-3
      - IN: triggertest3
      - TASK:
        - script: ./IN/sample-script-4/sample-script-4/echo.sh
    on_success:
      #- uname -a
      - NOTIFY: myEmail2
      - NOTIFY: mySlack2
      - echo 'infra test'
      - echo 'newtesting success'
    on_failure:
      - echo 'testing1 failure'
      - echo 'failure runSh'
      - NOTIFY: mySlack2
  
 
