jobs:
  - name: runSh35
    type: runSh
    steps:
      - IN: sample-script-3
      - IN: triggertest3
      - TASK:
        - script: ./IN/sample-script-3/sample-script-3/echo.sh
    on_success:
      - uname -a
     # - NOTIFY: myEmail2
      - echo 'infra test'
    on_failure:
      - echo 'testing failure'
      - NOTIFY: mySlack2
  
 
