jobs:
  - name: plv2-manT11
    type: manifest
    steps:
      - IN: plv2-imageT1j1
        versionNumber: 10000
      #- IN: plv2-envimage
      - IN: triggertestT1
  - name: runShT1
    type: runSh
   # serial: true
    steps:
      - IN: sample-scriptT1
      - IN: plv2-manT11
      #- IN: runShT1
      #- OUT: plv2-imageT1 
     # - IN: SREYA
     # - IN: env1
     # - IN: plv2-imageT1
        #versionName: "deploy.1"
      - IN: triggertestT1
      - TASK:
        - script: ./IN/sample-scriptT1/gitRepo/echo.sh
        - script: pwd
        - script: ls
        - script: export FOO=bar
        - script: export FOO1=bar1
        - script: echo $FOO && echo $FOO1
        - script: echo $n1
        # - script: "node --version"
        # - script: echo "$foo"
        # - script: echo "$n1"
        # - script: echo 'new'
        #- script: "sudo apt-get install tree"
    on_success:
       - script: pwd
       - script: ls /build
       - script: /build/IN/sample-scriptT1/gitRepo/echo.sh
       - NOTIFY: myEmail2
       - NOTIFY: mySlack2
       - echo 'infra test'
       - echo 'newtesting success'
    #   - NOTIFY: mySlack2
    #   - NOTIFY: myEmail2
    on_failure:
      -  echo 'testing1 failure'
      -  echo 'failure runSh'
      -  pwd
      -  ls
      - NOTIFY: mySlack2
      - NOTIFY: myEmail2
    on_start:
    #   - script: echo 'strat test'
    #   - script: echo 'test'
    #   - script: ls
      - NOTIFY: mySlack2
      - NOTIFY: myEmail2
    #   - NOTIFY: mySlack2
  
  - name: runShT111
    type: runSh
  # #  serial: true
    steps:
      - IN: sample-scriptT11
      - IN: triggertestT1
      - OUT: env1
  #     #- IN: runShT1
      - TASK:
        - script: ./IN/sample-scriptT11/gitRepo/echo.sh
  - name: runShTL1
    type: runSh
  # #  serial: true
    steps:
      - IN: sample-scriptT1k1
      - IN: triggertestT1
      #- OUT: env1
  #     #- IN: runShT1
      - TASK:
        - script: ./IN/sample-scriptT1k1/gitRepo/echo.sh
      

 
